### ISSUE TITLE
Подключиться к фтп

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/unity-dana#1]
Это доступы к серваку где будет лежать xml выгрузка товаров. Там же будут и картинки. Надо попробовать подключиться к этому серверу:

IP 192.168.0.95
login: ASRV
pass: nimda-unity2016

**Comment by kkan** [comment]
Вот что выдал сайт https://ftptest.net/: 
`You entered a private IP address. Those are not routed. If you want others to connect to your server you need to use a global address.`
