### ISSUE TITLE
Личный кабинет для юр.лиц

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#12]
Заменить поля реквизитов на:
- Полное наименование организации 
- Юридический адрес 
- ИНН
- ОГРН
- ОКПО
- ОКАТО 
- Реквизиты банка (текстовое поле)

![image](https://cloud.githubusercontent.com/assets/18350195/15934227/15122e9a-2e63-11e6-99e2-0c579a31947b.png)

**Comment by adFedorovich** [comment]
Done

**Comment by yuliyakislach** [comment]
textarea  для поля "Реквизиты банка"
