### ISSUE TITLE
Правки верстка

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#13]
Вернуть карту http://test.ud.staging.dshop24.by/contacts

Запретить аутлайн на сайте (Обводка элементов): 
![image](https://cloud.githubusercontent.com/assets/8914398/16116291/afce42a4-33d4-11e6-8aeb-bdd18fe6621d.png)

**Comment by yuliyakislach** [comment]
![image](https://cloud.githubusercontent.com/assets/18350195/15935333/2900afd6-2e67-11e6-9855-53cac79c7c74.png)
уменьшить

**Comment by camorazrushimoe** [comment]
@yuliyakislach  Карта должна быть на всю ширину экрана?
![image](https://cloud.githubusercontent.com/assets/8914398/16116272/9dddcca4-33d4-11e6-9331-e466c9198196.png)
