### ISSUE TITLE
Правки верстка

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/unity-dana#16]
шрифт хлебных крошек
![2016-06-24 13 00 51](https://cloud.githubusercontent.com/assets/18350195/16334773/9f0015a0-3a0b-11e6-878e-9482115d7a1c.png)

**Comment by adFedorovich** [comment]
Реализовал HTML

**Comment by yuliyakislach** [comment]
Добавить руку для всех кликабельных элементов
поиск
![2016-06-30 16 21 21](https://cloud.githubusercontent.com/assets/18350195/16489494/89e70124-3ede-11e6-8e9b-5a4158ec60e4.png)

**Comment by yuliyakislach** [comment]
Стилизовать попап "Вы успешно подписаны на рассылку!" 
![2016-07-01 18 08 37](https://cloud.githubusercontent.com/assets/18350195/16525799/bc60fbea-3fb6-11e6-95ee-8a469b43ce5c.png)
