### ISSUE TITLE
Оформление заказа

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/unity-dana#19]
Выводить реальный номер заказа при оформлении покупки
![2016-07-13 13 57 40](https://cloud.githubusercontent.com/assets/18350195/16801118/8c99585e-4901-11e6-8637-aa0b2522e115.png)

История заказов
нет названия, цены, количества
![2016-07-13 13 59 06](https://cloud.githubusercontent.com/assets/18350195/16801135/a67e8d8e-4901-11e6-9835-f68b0ea9199d.png)

**Comment by yuliyakislach** [comment]
добавлена верстка для страницы, которая должна выскакивать после нажатия на кнопку 
![2016-06-23 15 25 24](https://cloud.githubusercontent.com/assets/18350195/16302979/c4790428-3956-11e6-9d50-d640fe3816c2.png)

**Comment by yuliyakislach** [comment]
![2016-07-13 13 57 40](https://cloud.githubusercontent.com/assets/18350195/16801118/8c99585e-4901-11e6-8637-aa0b2522e115.png)

**Comment by yuliyakislach** [comment]
История заказов
![2016-07-13 13 59 06](https://cloud.githubusercontent.com/assets/18350195/16801135/a67e8d8e-4901-11e6-9835-f68b0ea9199d.png)

**Comment by gitwhatislove** [comment]
#51
