### ISSUE TITLE
Страница после оформления заказа

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/unity-dana#20]
В корзине, после оформления заказа. Пользователь должен попадать на страницу успешного заказа. На этой странице должен отображаться: 
- весь его заказ. Перечень товаров, их кол-во стоимость
- Текст "Вы успешно оформили заказ. В ближайшее время мы с Вами свяжемся"
- Номер заказа

@candalik для не зарегистрированного пользователя. После оформления заказа пользователь становится зарегистрированным и авторизированным. 

@adFedorovich Необходимо подготовить html верстку такой страницы

**Comment by AndreyFedarovich** [comment]
Сделал не отдельной страницей (а так же как и когда козина пуста) Но если Жене нужна страница, то я могу сверстать ее, просто тогда нужно создать ее шаблон на ангуляре
