### ISSUE TITLE
Новая выгрузка

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/unity-dana#28]
Сделали новую выгрузку, по идее она доступна по адресу:
\WS2008\c$\1C\Exchange\САЙТ

Там должна быть информация о картинках. Где квадратная, а где прямоугольная. Так же должна быть информация по структуре каталога. 

@v-kabashnikov Вопрос в автоматическом обновлении всего этого дела. Рельсы должны сами проверять сервер и скачивать оттуда выгрузку. И при необходимости обновлять каталог товаров.

**Comment by yuliyakislach** [comment]
NotificationType 02 -  в печати
