### ISSUE TITLE
Журналы

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#29]
**Исправить ошибку ПерИодичность**

 Поля товаров в соответсвии с макетом
- Классификатор NIION
- ПерИодичность
- Специализация
- Профиль журнала

**Остальные - просто поле Content**

Выводить для категории товаров "Журналы" в соответствии с макетом
http://test.ud.dshop24.by/template/magDetails.html

![2016-07-07 17 02 53](https://cloud.githubusercontent.com/assets/18350195/16655738/7b593074-4464-11e6-9c37-ecceb78c4788.png)

**Comment by gitwhatislove** [comment]
Добавить поля descript
