### ISSUE TITLE
Футер

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#34]
Закрепить внизу экрана
![2016-07-04 17 47 48](https://cloud.githubusercontent.com/assets/18350195/16564266/34dda456-420f-11e6-8316-36f69d26a30c.png)

**Comment by gitwhatislove** [comment]
страницы post

**Comment by yuliyakislach** [comment]
![2016-07-07 16 35 48](https://cloud.githubusercontent.com/assets/18350195/16654911/9e0ca596-4460-11e6-98f8-13fb6dcab2d1.png)
