### ISSUE TITLE
Восстановление пароля

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#37]
**После замены пароля - отправлять пользователя в личный кабинет**

**Comment by gitwhatislove** [comment]
иии? должно вести на отдельную страницу?

**Comment by yuliyakislach** [comment]
в смысле? оно просто выдает ошибку
должно писать что-то вроде "Пароль успешно изменен."
и перекидывать на главную, а еще лучше в личный кабинет

**Comment by gitwhatislove** [comment]
В личный кабинет не получится, пользователь не авторизирован. Отправляю на главную
