### ISSUE TITLE
Поля книг

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#45]
Тема - Категория товара
Автор  - Author
Полное наименование
ISBN   -                              Isbn
Вид переплета
Страницы кол-во     -       Pages amount
Аннотация               -        Description  
Цена                        -         Price

![2016-07-13 18 01 31](https://cloud.githubusercontent.com/assets/18350195/16808071/a91b7fda-4923-11e6-91c2-e2a864315d3e.png)

**Comment by gitwhatislove** [comment]
у товара нет поля автор.

**Comment by gitwhatislove** [comment]
Вид переплета
