### ISSUE TITLE
вопросы

### ISSUE THREAD

**Issue by savushkin-yauheni** [digitalshop24/unity-dana#5]
http://test.ud.dshop24.by/template/catDetails.html
1. под редакцией. что за поле в апи ?
2. Изд-во ЮНИТИ, 2014   что это за поле/поля ?
3. 60x90/16 это что ?
4.  Какая-то определенная тематика  что за поле ?
5. капча на реге. чья, лоткуда, надо тогда апи тоже

**Comment by camorazrushimoe** [comment]
1. Под ред. Н.Ш. Кремера (Под. ред. - оставляем пустым, нет такого, надо будет добавлять)
2. Изд-во ЮНИТИ, 2014  (Изд-во:  publisher_name )
3. Это вот эти параметры:
   "height": "26",
   "width": "21",
   "length": "04",
4. Это рубрика к которой относиться книга. По идее в апи вот она "theme": " Зарубежный учебник",
