### ISSUE TITLE
Главная

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#53]
Правки по главной
![1_](https://cloud.githubusercontent.com/assets/18350195/16872078/53b3faa6-4a93-11e6-85d7-947e783c7a45.jpg)

Как должно стать
![1_](https://cloud.githubusercontent.com/assets/18350195/16872079/54c827a0-4a93-11e6-9f8e-ef42679d9d6a.jpg)

**Comment by yuliyakislach** [comment]
Убрать переход при перетягивании слайдера

**Comment by gitwhatislove** [comment]
На главной не делал, полосу снизу и подчеркивание хедера тоже не делал
