### ISSUE TITLE
Выгрузка Журналы

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#54]
Новый раздел в админке "Журналы" - Выгрузка

http://niion.org/project/

Основной журнал - категория
Выпуски журнала - странички pdf
Все названия в админке - на русском языке

убрать у книг
![2016-07-18 15 33 33](https://cloud.githubusercontent.com/assets/18350195/16914762/b273616a-4cfc-11e6-9912-e71e0b21b45b.png)
![2016-07-18 15 35 26](https://cloud.githubusercontent.com/assets/18350195/16914787/d30c0f58-4cfc-11e6-8697-4a52a1b685e9.png)

**Comment by v-kabashnikov** [comment]
рубрики - отдельная моделька с одним тестовым полем html редактор
