### ISSUE TITLE
Вход в админку

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#63]
Стилизовать
![2016-07-21 13 49 21](https://cloud.githubusercontent.com/assets/18350195/17020303/79b16f26-4f49-11e6-8747-25c0b0739046.png)
как то так
![2016-07-21 13 54 45](https://cloud.githubusercontent.com/assets/18350195/17020435/39800c36-4f4a-11e6-8523-3d7f987b5fe4.png)
убрать все синие ссылки ниже

**Comment by gitwhatislove** [comment]
не ко мне таска это к ване скорее

**Comment by yuliyakislach** [comment]
![2016-07-25 17 00 51](https://cloud.githubusercontent.com/assets/18350195/17106852/8e85fcec-5295-11e6-9cc2-0a8c3ba3feeb.png)
убери крутелку, пожалуйста)

**Comment by v-kabashnikov** [comment]
(((((((((((

**Comment by kkan** [comment]
@yuliyakislach а мне тоже нравилось:(

**Comment by yuliyakislach** [comment]
и мне понравилось, особенно с аутлайном) но нет)
