### ISSUE TITLE
Не работает регистрация

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#71]
![2016-07-26 10 41 03](https://cloud.githubusercontent.com/assets/18350195/17129669/2771f6b8-531d-11e6-9278-2437071bd0c1.png)

**Comment by gitwhatislove** [comment]
Ваня посмотри логи, регистрация работает магически.
- Сначала она не работала. Мне не приходил ответ.
- Потом я попробовал зарегаться из апидока, там зарегало норм.
- Потом попробовал с сайта, все заработало.))
