### ISSUE TITLE
правки

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#75]
на сайте 3 выпуска
![2016-07-26 13 09 31](https://cloud.githubusercontent.com/assets/18350195/17134137/a6382972-5331-11e6-8e52-00ff648c50a5.png)

в админке для редактора 1 выпуск
![2016-07-26 13 09 46](https://cloud.githubusercontent.com/assets/18350195/17134145/adf5df10-5331-11e6-89ea-da8ba196020b.png)

**Comment by yuliyakislach** [comment]
Добавить админу возможность редактировать раздел Requisit

**Comment by yuliyakislach** [comment]
Goods переименовать в "Книжная продукция"

**Comment by yuliyakislach** [comment]
![2016-07-26 13 36 31](https://cloud.githubusercontent.com/assets/18350195/17134897/80631ba4-5335-11e6-8f65-ae1853933ab7.png)

**Comment by v-kabashnikov** [comment]
норм все с этим?

**Comment by yuliyakislach** [comment]
нет, комментарии что остались все еще не работает

**Comment by v-kabashnikov** [comment]
вуаля
