### ISSUE TITLE
Названия в админке

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/unity-dana#9]
Обрезает названия книг на полуслове
![image](https://cloud.githubusercontent.com/assets/18350195/15707209/bd92f5ee-27f7-11e6-8362-62f71e5ae6f5.png)

**Comment by v-kabashnikov** [comment]
Это у них спроси,  у них также в выгрузке, из которой я все это парсил
<TitleText>Материалы "круглого стола", посвященного обсуждению кни</TitleText>
